spring.application.name=backend

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false

server.server-header=
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USERMAIL}
spring.mail.password=${PASSMAIL}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

cms.base-url=${CMS_BASE_URL}
cms.strapi.api-path=/api
cms.strapi.media-path=/uploads

cloudflare.turnstile.secret-key=${CAPTCHA_SECRET_KEY}