spring.application.name=backend

app.security.csp.enabled=false

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false

server.server-header=
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.shutdown=graceful

spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

cms.base-url=${CMS_HOST}
cms.strapi.api-path=/api
cms.strapi.media-path=/uploads

cloudflare.turnstile.secret-key=${CAPTCHA_SECRET_KEY}

spring.cache.type=redis
spring.data.redis.host=${CACHE_BASE_URL}
spring.data.redis.port=${CACHE_PORT}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false